# ?????????? ??????? ? ???????? ???????
spring.config.import=optional:file:/app/config/secret.properties
server.port=8080

# Remove later
# spring.datasource.url=jdbc:postgresql://auth-test-db.cozoggag0bjz.us-east-1.rds.amazonaws.com:5432/auth_test?sslmode=require
# spring.datasource.username=postgres
# spring.datasource.password=AuthDbStrongPass123!

# JWT_SECRET=local-dev-secret-1234567890
# JWT_EXPIRATION=86400000
